### ISSUE TITLE
After reboot service doesnt start

### ISSUE THREAD

**Issue by derGreyson** [MartinGrosse/venus.dbus-go-e-controller-smartmeter#1]
Hi,

i have a question, iam new to this. I got it running, but after a "reboot" i have to run "ln -s /data/dbus-go-e-controller-smartmeter/service /service/dbus-go-e-controller-smartmeter" that line and the Service starts running.

maybe you can help me what i have done wrong.

**Comment by MartinGrosse** [comment]
Just use nano and add this line (ln -s /data/dbus-go-e-controller-smartmeter/service /service/dbus-go-e-controller-smartmeter) in the file /data/rc.local

**Comment by derGreyson** [comment]
Thanks... now i understand so much more. thx
